project_id = "owtufhdsuuyrgmxytclj"

[functions.generate-social-assets]
verify_jwt = true

# Sitemap function configuration - MUST REMAIN DISABLED FOR PUBLIC ACCESS
[functions.simplified-sitemap]
verify_jwt = false

# Stripe webhook function - MUST REMAIN DISABLED FOR WEBHOOK ACCESS
[functions.stripe-webhook]
verify_jwt = false

