
project_id = "owtufhdsuuyrgmxytclj"

[global.env_variables]
# Environment variables can now be managed directly in Supabase dashboard

# Social media preview functions - MUST REMAIN DISABLED FOR SOCIAL MEDIA PREVIEWS
[functions.smart-link-seo]
verify_jwt = false

[functions.smart-link-meta]
verify_jwt = false

[functions.whatsapp-debug]
verify_jwt = false

# Stripe webhook function - MUST REMAIN DISABLED FOR WEBHOOK ACCESS
[functions.stripe-webhook]
verify_jwt = false

# Checkout session function with JWT verification
[functions.create-checkout-session]
verify_jwt = true

# Payment verification function
[functions.verify-payment-session]
verify_jwt = true
