import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        perfume: "#E5D4FF",
        rhino: "#2E4374",
        meteorite: "#3B185F",
        regentBlue: "#A0E9FF",
        arapawa: "#0B2447",
        ziggurat: "#A5D7E8",
        blueGem: "#4424D6",
        surfCrest: "#C8E4B2",
        mintGreen: "#9FFF9C",
        toreaBay: "#0B2447",
        persianBlue: "#1D24CA",
        nebula: "#1D267D",
        moonRaker: "#E5D4FF",
        jacarta: "#3B185F",
        jordyBlue: "#9BB8CD",
        persianIndigo: "#2E4374",
        bilobaFlower: "#C4B0FF",
        luckyPoint: "#2E2E7E",
        jaggedIce: "#C4DFDF",
        christalle: "#2E4374",
        cornflowerBlue: "#7B66FF",
        mindaro: "#D4FF9C",
        snowyMint: "#DBFFD6",
        valhalla: "#2E2E7E",
        codGray: "#121212",
        bermuda: "#93FFD8",
        tropicalBlue: "#C4DFDF",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        heading: ["Poppins", "sans-serif"],
      },
      backgroundImage: {
        'hero-gradient': 'linear-gradient(135deg, #7B66FF, #E5D4FF)',
        'cta-gradient': 'linear-gradient(135deg, #9FFF9C, #0B2447)',
        'feature-gradient-1': 'linear-gradient(135deg, #E5D4FF, #3B185F)',
        'feature-gradient-2': 'linear-gradient(135deg, #A5D7E8, #4424D6)',
        'feature-gradient-3': 'linear-gradient(135deg, #C8E4B2, #0B2447)',
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    require('@tailwindcss/typography'),
  ],
} satisfies Config;