project_id = "owtufhdsuuyrgmxytclj"

# Set import map for dependencies
import_map = "../_shared/import_map.json"

# Required environment variables for this function
[config]
env_vars = [
  "OPENAI_API_KEY",
  "SUPABASE_URL",
  "SUPABASE_SERVICE_ROLE_KEY"
] 