name: Deploy Supabase Edge Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/functions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v2

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: |
          supabase functions deploy --project-ref $PROJECT_ID 