
name: Deploy WhatsApp Debug Function

on:
  push:
    branches:
      - main  # or your default branch name
    paths:
      - 'supabase/functions/whatsapp-debug/**'
      - 'supabase/config.toml'
      - '.github/workflows/deploy-whatsapp-debug.yml'

jobs:
  deploy-whatsapp-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Login to Supabase
        run: supabase login
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Link to Supabase project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}

      - name: Update config.toml for whatsapp-debug
        run: |
          # Ensure the function-specific config.toml exists and has verify_jwt = false
          mkdir -p supabase/functions/whatsapp-debug
          echo 'project_id = "${{ secrets.SUPABASE_PROJECT_ID }}"' > supabase/functions/whatsapp-debug/config.toml
          echo '' >> supabase/functions/whatsapp-debug/config.toml
          echo '[functions.whatsapp-debug]' >> supabase/functions/whatsapp-debug/config.toml
          echo 'verify_jwt = false' >> supabase/functions/whatsapp-debug/config.toml
          
          # Also update the main config.toml if it exists
          if [ -f "supabase/config.toml" ]; then
            # Check if whatsapp-debug config exists in the file
            if grep -q "\[functions.whatsapp-debug\]" "supabase/config.toml"; then
              # Replace verify_jwt if it exists
              sed -i 's/\(\[functions\.whatsapp-debug\].*\n.*verify_jwt\s*=\s*\)true/\1false/g' supabase/config.toml
            else
              # Add the configuration if it doesn't exist
              echo '' >> supabase/config.toml
              echo '# WhatsApp debug function - MUST REMAIN DISABLED FOR SOCIAL PREVIEWS' >> supabase/config.toml
              echo '[functions.whatsapp-debug]' >> supabase/config.toml
              echo 'verify_jwt = false' >> supabase/config.toml
            fi
          fi

      - name: Deploy whatsapp-debug function with JWT verification disabled
        run: supabase functions deploy whatsapp-debug --no-verify-jwt
