
name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Login to Supabase
        run: supabase login ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        
      - name: Make deploy script executable
        run: chmod +x ./supabase/deploy-functions.sh
        
      - name: Deploy functions using custom script
        run: ./supabase/deploy-functions.sh
        env:
          SUPABASE_PROJECT_ID: owtufhdsuuyrgmxytclj
          
      - name: Generate Simple Function Deployment Report
        run: |
          echo "## Edge Function Deployment Report" > deployment_report.md
          echo "### Deployed Functions" >> deployment_report.md
          supabase functions list -p owtufhdsuuyrgmxytclj | grep -v "^$" | sed 's/^/- /' >> deployment_report.md
          
          # Don't inspect functions as it triggers JWT resets - just output deployment status
          echo "### Deployment Status" >> deployment_report.md
          echo "Functions were deployed with their respective JWT verification settings according to the .no-verify-jwt markers." >> deployment_report.md
          echo "See deploy-functions.sh logs for verification details." >> deployment_report.md
          
          cat deployment_report.md
