name: Deploy Sitemap Function

on:
  push:
    branches:
      - main  # or your default branch name
    paths:
      - 'supabase/functions/simplified-sitemap/**'
      - 'supabase/config.toml'
      - '.github/workflows/deploy-sitemap-functions.yml'

jobs:
  deploy-sitemap-function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Login to Supabase
        run: supabase login
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Link to Supabase project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}

      - name: Update main config.toml for sitemap function
        run: |
          # Ensure the main config.toml has the simplified-sitemap function with verify_jwt = false
          if [ -f "supabase/config.toml" ]; then
            # Check if simplified-sitemap config exists in the file
            if ! grep -q "\[functions.simplified-sitemap\]" "supabase/config.toml"; then
              # Add the configuration if it doesn't exist
              echo '' >> supabase/config.toml
              echo '# Sitemap function configuration - MUST REMAIN DISABLED FOR PUBLIC ACCESS' >> supabase/config.toml
              echo '[functions.simplified-sitemap]' >> supabase/config.toml
              echo 'verify_jwt = false' >> supabase/config.toml
            fi
          fi

      - name: Update function-specific config.toml file
        run: |
          # Ensure the simplified-sitemap function has its own config.toml with verify_jwt = false
          if [ -d "supabase/functions/simplified-sitemap" ]; then
            mkdir -p "supabase/functions/simplified-sitemap"
            echo '# IMPORTANT: This is a public function that must remain accessible without authentication' > "supabase/functions/simplified-sitemap/config.toml"
            echo 'project_id = "${{ secrets.SUPABASE_PROJECT_ID }}"' >> "supabase/functions/simplified-sitemap/config.toml"
            echo 'verify_jwt = false' >> "supabase/functions/simplified-sitemap/config.toml"
            echo '' >> "supabase/functions/simplified-sitemap/config.toml"
          fi

      - name: Deploy simplified sitemap function with JWT verification disabled
        run: |
          if [ -d "supabase/functions/simplified-sitemap" ]; then
            supabase functions deploy simplified-sitemap --no-verify-jwt
          fi 