
name: Deploy Smart Link SEO Function

on:
  push:
    branches:
      - main  # or your default branch name
    paths:
      - 'supabase/functions/smart-link-seo/**'
      - 'supabase/functions/smart-link-meta/**'
      - 'supabase/config.toml'
      - '.github/workflows/deploy-smart-link-seo.yml'

jobs:
  deploy-smart-link-seo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Login to Supabase
        run: supabase login
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Link to Supabase project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
      
      # Deploy smart-link-seo function
      - name: Deploy smart-link-seo function with JWT verification disabled
        run: supabase functions deploy smart-link-seo --no-verify-jwt
        
      # Deploy smart-link-meta function
      - name: Deploy smart-link-meta function with JWT verification disabled  
        run: supabase functions deploy smart-link-meta --no-verify-jwt
