name: Deploy Stripe Webhook Function

on:
  push:
    branches:
      - main  # or your default branch name
    paths:
      - 'supabase/functions/stripe-webhook/**'
      - 'supabase/config.toml'
      - '.github/workflows/deploy-stripe-webhook.yml'

jobs:
  deploy-stripe-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Login to Supabase
        run: supabase login
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Link to Supabase project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}

      - name: Update config.toml for stripe-webhook
        run: |
          # Ensure the function-specific config.toml exists and has verify_jwt = false
          mkdir -p supabase/functions/stripe-webhook
          echo 'project_id = "${{ secrets.SUPABASE_PROJECT_ID }}"' > supabase/functions/stripe-webhook/config.toml
          echo '' >> supabase/functions/stripe-webhook/config.toml
          echo '[functions.stripe-webhook]' >> supabase/functions/stripe-webhook/config.toml
          echo 'verify_jwt = false' >> supabase/functions/stripe-webhook/config.toml
          
          # Also update the main config.toml if it exists
          if [ -f "supabase/config.toml" ]; then
            # Check if stripe-webhook config exists in the file
            if grep -q "\[functions.stripe-webhook\]" "supabase/config.toml"; then
              # Replace verify_jwt if it exists
              sed -i 's/\(\[functions\.stripe-webhook\].*\n.*verify_jwt\s*=\s*\)true/\1false/g' supabase/config.toml
            else
              # Add the configuration if it doesn't exist
              echo '' >> supabase/config.toml
              echo '# Stripe webhook function - MUST REMAIN DISABLED FOR WEBHOOK ACCESS' >> supabase/config.toml
              echo '[functions.stripe-webhook]' >> supabase/config.toml
              echo 'verify_jwt = false' >> supabase/config.toml
            fi
          fi

      - name: Deploy stripe-webhook function with JWT verification disabled
        run: supabase functions deploy stripe-webhook --no-verify-jwt 