
name: Deploy Smart Link Meta Function

on:
  push:
    branches:
      - main  # or your default branch name
    paths:
      - 'supabase/functions/smart-link-meta/**'
      - 'supabase/config.toml'
      - '.github/workflows/deploy-smart-link-meta.yml'

jobs:
  deploy-smart-link-meta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Login to Supabase
        run: supabase login
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Link to Supabase project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}

      - name: Update config.toml for smart-link-meta
        run: |
          # Ensure the function-specific config.toml exists and has verify_jwt = false
          mkdir -p supabase/functions/smart-link-meta
          echo 'project_id = "${{ secrets.SUPABASE_PROJECT_ID }}"' > supabase/functions/smart-link-meta/config.toml
          echo '' >> supabase/functions/smart-link-meta/config.toml
          echo '[functions.smart-link-meta]' >> supabase/functions/smart-link-meta/config.toml
          echo 'verify_jwt = false' >> supabase/functions/smart-link-meta/config.toml
          
          # Also update the main config.toml if it exists
          if [ -f "supabase/config.toml" ]; then
            # Check if smart-link-meta config exists in the file
            if grep -q "\[functions.smart-link-meta\]" "supabase/config.toml"; then
              # Replace verify_jwt if it exists
              sed -i 's/\(\[functions\.smart-link-meta\].*\n.*verify_jwt\s*=\s*\)true/\1false/g' supabase/config.toml
            else
              # Add the configuration if it doesn't exist
              echo '' >> supabase/config.toml
              echo '# Meta data function - MUST REMAIN DISABLED FOR SOCIAL PREVIEWS' >> supabase/config.toml
              echo '[functions.smart-link-meta]' >> supabase/config.toml
              echo 'verify_jwt = false' >> supabase/config.toml
            fi
          fi

      - name: Deploy smart-link-meta function with JWT verification disabled
        run: supabase functions deploy smart-link-meta --no-verify-jwt
