
name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Login to Supabase
        run: supabase login ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        
      - name: Make deploy script executable
        run: chmod +x ./supabase/deploy-functions.sh
        
      - name: Deploy functions using custom script
        run: ./supabase/deploy-functions.sh
        env:
          SUPABASE_PROJECT_ID: owtufhdsuuyrgmxytclj
          
      - name: Generate Function Deployment Report
        run: |
          echo "## Edge Function Deployment Report" > deployment_report.md
          echo "### Deployed Functions" >> deployment_report.md
          supabase functions list -p owtufhdsuuyrgmxytclj | grep -v "^$" | sed 's/^/- /' >> deployment_report.md
          echo "### JWT Verification Status" >> deployment_report.md
          echo "| Function | JWT Verification |" >> deployment_report.md
          echo "|----------|-----------------|" >> deployment_report.md
          for func in $(supabase functions list -p owtufhdsuuyrgmxytclj); do
            if [ -n "$func" ]; then
              status=$(supabase functions inspect $func -p owtufhdsuuyrgmxytclj --json | grep -o '"verify_jwt":[^,}]*' | cut -d':' -f2)
              echo "| $func | $status |" >> deployment_report.md
            fi
          done
          
          cat deployment_report.md
          
          echo "::set-output name=report::$(cat deployment_report.md)"

